apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-container
  template:
    metadata:
      labels:
        app: api-container
    spec:
      containers:
        - name: sterling-user-api
          image: prunedge/sterling-user-api
          command: ["gunicorn --bind 0.0.0.0:10050 core.asgi -w 4 -k uvicorn.workers.UvicornWorker"]
          imagePullPolicy: Always
          ports:
            - containerPort: 10050
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_name

            - name: ACCESS_KEY_AWS
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: aws_access_key

            - name: ACCESS_SECRET_AWS
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: aws_secret_key

            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: sendgrid_api_key

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: database_url

            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: api-credentials
                  key: SECRET_KEY

            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: api-credentials
                  key: DATABASE


#  SQL_ENGINE: "django.db.backends.postgresql"
#  DATABASE_URL: ""
#  REDIS_URL: "redis://default:redispw@redis:6379"
#  AWS_SQS_QUEUE: "sterling-dev-queue"
#  FLOWER_BASIC_AUTH: "admin:user_admin"
#  APP_NAME: "sterling-auth"
#  ACCESS_BUCKET_NAME_AWS: "sterling-retail-dev"
#  AWS_S3_REGION_NAME: "eu-west-3"
#  AWS_S3_CUSTOM_DOMAIN: "d1booj4nx6xvp.cloudfront.net"
#  CLOUDFRONT_ID: "E2EXJ9QGGNL7G4"
#  SMTP_HOST: "smtp.sendgrid.net"
#  SENDER_EMAIL: "noreply@prunedge.com"
#  CLIENT_URL: "https://sterling.netlify.app"
#  SENTRY_DSN: ""



