apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  aws_access_key: QUtJQTJPQzJVRDRPUE5YNFZaWDI=
  aws_secret_key: cVVRMUhGZU1Ea1RYOVJIWmhqaklhUkU0QU9iTmFza1VONlp2MlRTRw==
  sendgrid_api_key: U0cuY2JSZXhaNURSRy1zZFNCbTlfdGdXUS5lRUhUa3pCZ08zMXVld1NhOEluc3NzbGFtVkFMMkhFNUhsZmRhRVFuank0
